# Generated by Django 5.1.3 on 2026-01-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_unit',
            field=models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Legal', 'Legal'), ('EBU', 'EBU'), ('CBU', 'CBU'), ('COPS', 'COPS'), ('MPESA', 'MPESA'), ('HR', 'HR'), ('Corporate Affairs', 'Corporate Affairs'), ('MD', 'MD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_level',
            field=models.CharField(blank=True, choices=[('Director', 'Director'), ('Senior Manager', 'Senior Manager'), ('Manager', 'Manager')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('South', 'South'), ('Centre', 'Centre'), ('North', 'North')], max_length=20, null=True),
        ),
    ]
