# Generated by Django 5.1.6 on 2026-01-21 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tours.visit')),
            ],
        ),
    ]
