# Generated by Django 5.1.6 on 2026-01-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='prep_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='prep_other_comments',
            field=models.TextField(blank=True),
        ),
    ]
