# Generated by Django 5.1.3 on 2026-01-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_visit_prep_other_visit_prep_other_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='area_category',
            field=models.CharField(choices=[('Network Sites', 'Network Sites'), ('Data Centre', 'Data Centre'), ('Transmissions', 'Transmissions'), ('Network Other', 'Network Other'), ('Office', 'Office'), ('Warehouses', 'Warehouses'), ('Retail & Trade', 'Retail & Trade'), ('Events', 'Events'), ('Fleet', 'Fleet'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
